source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'JTAppleCalendar_Example', :exclusive => true do
  pod 'JTAppleCalendar', :path => '../'
end

target 'JTAppleCalendar_Tests', :exclusive => true do
  pod 'JTAppleCalendar', :path => '../'

  
end
